parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    #env(DATABASE_URL): ''
    env(DATABASE_USERNAME): '/run/secrets/database_username'
    env(DATABASE_PASSWORD): '/run/secrets/database_password'
    database_name: '%env(resolve:DATABASE_NAME)%'
    database_port: '%env(resolve:DATABASE_PORT)%'
    database_host: '%env(resolve:DATABASE_HOST)%'
    database_username: '%env(file:DATABASE_USERNAME)%'
    database_password: '%env(file:DATABASE_PASSWORD)%'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        #url: '%env(resolve:DATABASE_URL)%'
        dbname: '%database_name%'
        host: '%database_host%'
        port: '%database_port%'
        user: '%database_username%'
        password: '%database_password%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
